name: RecSearchR
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-annotate
  - bioconductor-annotationdbi
  - bioconductor-annotationfilter
  - bioconductor-annotationhub
  - bioconductor-ballgown
  - bioconductor-biobase
  - bioconductor-biocfilecache
  - bioconductor-biocgenerics
  - bioconductor-biocparallel
  - bioconductor-biomart
  - bioconductor-biostrings
  - bioconductor-biovizbase
  - bioconductor-bsgenome
  - bioconductor-ensembldb
  - bioconductor-genefilter
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - bioconductor-genomicalignments
  - bioconductor-genomicfeatures
  - bioconductor-genomicranges
  - bioconductor-ggbio
  - bioconductor-ggtree
  - bioconductor-graph
  - bioconductor-interactivedisplaybase
  - bioconductor-iranges
  - bioconductor-limma
  - bioconductor-organismdbi
  - bioconductor-protgenerics
  - bioconductor-plyranges
  - bioconductor-rbgl
  - bioconductor-rhtslib
  - bioconductor-rsamtools
  - bioconductor-rtracklayer
  - bioconductor-s4vectors
  - bioconductor-summarizedexperiment
  - bioconductor-sva
  - bioconductor-treeio
  - bioconductor-variantannotation
  - bioconductor-xvector
  - bioconductor-zlibbioc
  - bioconductor-plyranges
  - blas
  - r-ape
  - r-base=3.6.2
  - r-biocmanager
  - r-cowplot
  - r-data.table
  - r-essentials
  - r-geiger
  - r-generics
  - r-getopt
  - r-ggplotify
  - r-ggpubr
  - r-ggrepel
  - r-ggsci
  - r-ggsignif
  - r-gistr
  - r-git2r
  - r-packrat
  - r-plotly
  - r-reshape2
  - r-reticulate
  - r-devtools
  - r-tidytree
  - r-tidyverse
  - r-tinytex
  - r-upsetr
  - r-viridis
  - r-viridislite
  - r-workflowr
  - rpy2
  - rstudio
  - snakemake-minimal
