name: Alignment
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - hisat2
  - stringtie
  - samtools
  - parallel
  - snakemake-minimal
  - sra-tools  
  - gffutils
  - openssl=1.0
  - bedops
  - python =3.6
  - pandas
