name: RecBlat
channels:
  - bioconda
  - conda-forge
  - r
dependencies:
  - snakemake-minimal =5.2.4
  - python =3.6
  - r =3.5.1
  - r-essentials
#  - r-reshape2
#  - r-ape
#  - r-rcolorbrewer
#  - r-viridis
#  - r-upsetr
  - rpy2
  - rstudio
  - r-git2r
  - jinja2 =2.10
  - networkx =2.1
  - matplotlib =2.2.3
  - graphviz =2.38.0
  - bcftools =1.9
  - samtools =1.9
  - hisat2
  - stringtie
  - sra-tools
  - Click =7.0
  - biopython =1.73
  - dill =0.2.8.2
  - multiprocess =0.70.6.1
  - mygene =3.1.0
  - nose =1.3.7
  - pandas = 0.23.4
  - wget
  - ucsc-fatotwobit
  - parallel
  - pip:
    - "-e git+https://github.com/docmanny/RecBlast#egg=RecBlast"